=== jtp-Bteam/XML/shogi.dtd
<!ENTITY % tejunlist "(sente | gote)">
<!ENTITY % komalist "(fu | kyo | kei | gin | kin | hi | kaku | ou | gyoku)">
<!ENTITY % bool "(true | false)">
<!ENTITY % mochigomalist "(true | false | restall )">
<!ENTITY % zahyo "(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9)">
<!ELEMENT shogi (koma*)>
<!ELEMENT koma EMPTY>
<!ATTLIST koma
	  tejun %tejunlist; #REQUIRED
	  name %komalist; #IMPLIED
	  nari %bool; #IMPLIED
	  mochigoma %mochigomalist; #IMPLIED
	  x %zahyo; #IMPLIED
	  y %zahyo; #IMPLIED>

=== jtp-Bteam/XML/shogi2.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE shogi SYSTEM "shogi.dtd">
<shogi>
  <koma tejun="sente" name="gin"  mochigoma="true" />
  <koma tejun="sente" name="gin" x="5" y="3" />
  <koma tejun="sente" name="kaku" nari="true" x="8" y="5" />
  <koma tejun="gote" mochigoma="restall" />
  <koma tejun="gote" name="gin" x="4" y="1" />
  <koma tejun="gote" name="ou" x="5" y="1" />
  <koma tejun="gote" name="gin" x="6" y="1" />
</shogi>
